### ISSUE TITLE
No machine prefix for nfs

### ISSUE THREAD

**Issue by ThYpHo0n** [frgmt/vagrant-invade#5]
Hi,

after the update to the newest version we got issues with the generated Vagrant file.
Before the update:
https://gist.github.com/ThYpHo0n/b1eeac22aa1d504dc19631b7acee8228

After the update:
https://gist.github.com/ThYpHo0n/684e2f6b1b3cdbd917b91ff78ca5f475

**Comment by lennartstein** [comment]
Seems the machines name is not used inside the template. I will review this later this day. For now you should revert to latest version before update. I think it was 0.4.9 or 0.4.8.

**Comment by lennartstein** [comment]
Should be fixed with https://github.com/frgmt/vagrant-invade/commit/1e018ccce4d6f976df2b85143b1605ef0c3d2cf6

Update to version **0.5.3**
